// <auto-generated />
namespace SAH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Will_Migration_002 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Will_Migration_002));
        
        string IMigrationMetadata.Id
        {
            get { return "202104090130213_Will_Migration_002"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
