// <auto-generated />
namespace SAH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mahsa_update_appointment_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mahsa_update_appointment_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202104160358186_mahsa_update_appointment_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
