// <auto-generated />
namespace SAH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class the_final_barbara : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(the_final_barbara));
        
        string IMigrationMetadata.Id
        {
            get { return "202104201542320_the_final_barbara"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
