// <auto-generated />
namespace SAH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class diarra_mvp_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(diarra_mvp_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "202104090356431_diarra_mvp_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
