// <auto-generated />
namespace SAH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class danyal_improv : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(danyal_improv));
        
        string IMigrationMetadata.Id
        {
            get { return "202104261641508_danyal_improv"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
